# --- Local Profile (Docker) ---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/heemo
    username: heemo_user
    password: heemo_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        open-in-view: false

---
# --- Dev Profile (AWS Dev RDS) ---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DEV_DB_HOST}:5432/heemo
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        open-in-view: false

---
# --- Prod Profile (AWS Prod RDS) ---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:5432/heemo
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        open-in-view: false
