# --- Local Profile (Docker) ---
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379

---
# --- Dev Profile (AWS ElastiCache Dev) ---
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: 6379

---
# --- Prod Profile (AWS ElastiCache Prod) ---
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: 6379
